lib/cov_tracker_server_web/router.ex
defmodule CovTrackerServerWeb.Router do
  use CovTrackerServerWeb, :router
  import CovTrackerServerWeb.Plugs, only: [ensure_admin: 2]

  # Our pipeline implements "maybe" authenticated. We'll use the `:ensure_auth` below for when we need to make sure someone is logged in.
  pipeline :auth do
    plug CovTrackerServer.UserManager.Pipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # API
  scope "/api", CovTrackerServerWeb do
    pipe_through [:api]

    post "/login", UserController, :api_login
    post "/register", UserController, :api_register
  end

  # Maybe logged in routes
  scope "/", CovTrackerServerWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    # User login/registration
    get "/login", UserController, :login
    post "/login", UserController, :login_submit
    get "/logout", UserController, :logout

    get "/register", UserController, :register
    post "/register", UserController, :register_submit
  end

  # Definitely logged in scope
  scope "/", CovTrackerServerWeb do
    pipe_through [:browser, :auth, :ensure_auth]
  end

  # Admin panel
  scope "/admin", CovTrackerServerWeb do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]
    get "/", AdminController, :index
    get "/users", UserController, :list
    get "/users/infections", UserController, :infections
    get "/locations", LocationController, :list
  end

  # Other scopes may use custom stacks.
  # scope "/api", CovTrackerServerWeb do
  #   pipe_through :api
  # end
end

lib/cov_tracker_server_web/views/layout_view.ex
defmodule CovTrackerServerWeb.LayoutView do
  use CovTrackerServerWeb, :view
end

lib/cov_tracker_server_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CoVTracker</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
  </head>
  <body>
    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="<%= Routes.admin_path(@conn, :index) %>">
                    CovTracker Admin Panel
                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                    data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbar" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="<%= Routes.admin_path(@conn, :index) %>">
                        Dashboard
                    </a>
                    <a class="navbar-item" href="<%= Routes.location_path(@conn, :list) %>">
                        Location Updates
                    </a>
                    <a class="navbar-item" href="<%= Routes.user_path(@conn, :list) %>">
                        Users
                    </a>
                    <a class="navbar-item" href="<%= Routes.user_path(@conn, :infections) %>">
                        Infections
                    </a>
                </div>

                <div class="navbar-end">
                    <a class="navbar-item" href="<%= Routes.user_path(@conn, :logout) %>">
                        Logout
                    </a>
                </div>
            </div>
        </div>
    </nav>


    <div class="container">
      <%# Flash Messages %>
      <%
        success = get_flash(@conn, :success)
        error = get_flash(@conn, :error)
      %>

      <%# Success %>
      <%= if success do %>
      <div class="notification is-success is-light">
        <%= get_flash(@conn, :success) %>
      </div>
      <% end %>

      <%# Error %>
      <%= if error do %>
      <div class="notification is-danger is-light">
        <%= get_flash(@conn, :error) %>
      </div>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/cov_tracker_server_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CoVTracker Admin Panel</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <div class="container">
      <%# Flash Messages %>
      <%
        success = get_flash(@conn, :success)
        error = get_flash(@conn, :error)
      %>

      <%# Success %>
      <%= if success do %>
      <div class="notification is-success is-light">
        <%= get_flash(@conn, :success) %>
      </div>
      <% end %>

      <%# Error %>
      <%= if error do %>
      <div class="notification is-danger is-light">
        <%= get_flash(@conn, :error) %>
      </div>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>